//! Unsafe FFI bindings to vendored liburing 2.15 plus a thin, safe-ish control
//! plane (ring setup/teardown, capability probing) for the yxorp completion-native
//! runtime. Hot-path SQE/CQE handling lives in `runtime-core`.

#![allow(
    non_upper_case_globals,
    non_camel_case_types,
    non_snake_case,
    dead_code,
    // bindgen emits inline-fn helpers whose bodies predate edition-2024 unsafe rules.
    unsafe_op_in_unsafe_fn
)]

/// Raw liburing bindings generated by bindgen against the vendored 2.15 headers.
pub mod ffi {
    include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
}

/// Hand-declared externs for liburing's `static inline` helpers (bindgen skips them).
pub mod inline;

/// Runtime capability probing (`KernelCaps`).
pub mod caps;

pub use caps::KernelCaps;

#[cfg(test)]
mod link_smoke {
    use super::ffi;

    /// Proves the vendored liburing-ffi archive actually links: create and tear
    /// down a tiny ring. Skips cleanly where io_uring is unavailable (sandboxed CI).
    #[test]
    fn ring_init_and_exit_links() {
        unsafe {
            let mut ring: ffi::io_uring = std::mem::zeroed();
            let rc = ffi::io_uring_queue_init(4, &mut ring, 0);
            if rc < 0 {
                // ENOSYS / EPERM in a restricted sandbox — linking still succeeded.
                eprintln!("io_uring_queue_init unavailable here: {rc}");
                return;
            }
            ffi::io_uring_queue_exit(&mut ring);
        }
    }
}
